// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Dominio;

namespace Persistencia
{
    public partial class CursosonlineContext : DbContext
    {
        public CursosonlineContext()
        {
        }

        public CursosonlineContext(DbContextOptions<CursosonlineContext> options)
            : base(options)
        {
        }

        public DbSet<Comentario> Comentario { get; set; }
        public DbSet<Curso> Curso { get; set; }
        public DbSet<CursoInstructor> CursoInstructor { get; set; }
        public DbSet<Instructor> Instructor { get; set; }
        public DbSet<Precio> Precio { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<CursoInstructor>(entity =>
            {
                entity.HasKey(e => new { e.CursoId, e.InstructorId });
            });
        }
    }
}